// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bird "birdProtection/apps/gateway/internal/handler/bird"
	"birdProtection/apps/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/bird/add",
				Handler: bird.BirdAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/bird/update",
				Handler: bird.BirUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/bird/list",
				Handler: bird.BirListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/bird/get",
				Handler: bird.BirGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/bird/delete",
				Handler: bird.BirDeleteHandler(serverCtx),
			},
		},
	)
}
