// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: bird.proto

package birdservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BirdAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdName    string `protobuf:"bytes,1,opt,name=BirdName,proto3" json:"BirdName,omitempty"`
	BirdType    int64  `protobuf:"varint,2,opt,name=BirdType,proto3" json:"BirdType,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	PicUrl      string `protobuf:"bytes,4,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
}

func (x *BirdAddReq) Reset() {
	*x = BirdAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdAddReq) ProtoMessage() {}

func (x *BirdAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdAddReq.ProtoReflect.Descriptor instead.
func (*BirdAddReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{0}
}

func (x *BirdAddReq) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

func (x *BirdAddReq) GetBirdType() int64 {
	if x != nil {
		return x.BirdType
	}
	return 0
}

func (x *BirdAddReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BirdAddReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

type BirdAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID int64 `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
}

func (x *BirdAddResp) Reset() {
	*x = BirdAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdAddResp) ProtoMessage() {}

func (x *BirdAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdAddResp.ProtoReflect.Descriptor instead.
func (*BirdAddResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{1}
}

func (x *BirdAddResp) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

type BirdUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID      int64  `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
	BirdName    string `protobuf:"bytes,2,opt,name=BirdName,proto3" json:"BirdName,omitempty"`
	BirdType    int64  `protobuf:"varint,3,opt,name=BirdType,proto3" json:"BirdType,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	PicUrl      string `protobuf:"bytes,5,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
}

func (x *BirdUpdateReq) Reset() {
	*x = BirdUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdUpdateReq) ProtoMessage() {}

func (x *BirdUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdUpdateReq.ProtoReflect.Descriptor instead.
func (*BirdUpdateReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{2}
}

func (x *BirdUpdateReq) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

func (x *BirdUpdateReq) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

func (x *BirdUpdateReq) GetBirdType() int64 {
	if x != nil {
		return x.BirdType
	}
	return 0
}

func (x *BirdUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BirdUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

type BirdUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID int64 `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
}

func (x *BirdUpdateResp) Reset() {
	*x = BirdUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdUpdateResp) ProtoMessage() {}

func (x *BirdUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdUpdateResp.ProtoReflect.Descriptor instead.
func (*BirdUpdateResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{3}
}

func (x *BirdUpdateResp) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

type BirdListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	BirdType int64 `protobuf:"varint,3,opt,name=BirdType,proto3" json:"BirdType,omitempty"`
}

func (x *BirdListReq) Reset() {
	*x = BirdListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdListReq) ProtoMessage() {}

func (x *BirdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdListReq.ProtoReflect.Descriptor instead.
func (*BirdListReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{4}
}

func (x *BirdListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BirdListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BirdListReq) GetBirdType() int64 {
	if x != nil {
		return x.BirdType
	}
	return 0
}

type BirdListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*BirdListData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BirdListResp) Reset() {
	*x = BirdListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdListResp) ProtoMessage() {}

func (x *BirdListResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdListResp.ProtoReflect.Descriptor instead.
func (*BirdListResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{5}
}

func (x *BirdListResp) GetList() []*BirdListData {
	if x != nil {
		return x.List
	}
	return nil
}

type BirdListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID      int64  `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
	BirdName    string `protobuf:"bytes,2,opt,name=BirdName,proto3" json:"BirdName,omitempty"`
	BirdType    int64  `protobuf:"varint,3,opt,name=BirdType,proto3" json:"BirdType,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	PicUrl      string `protobuf:"bytes,5,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
}

func (x *BirdListData) Reset() {
	*x = BirdListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdListData) ProtoMessage() {}

func (x *BirdListData) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdListData.ProtoReflect.Descriptor instead.
func (*BirdListData) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{6}
}

func (x *BirdListData) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

func (x *BirdListData) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

func (x *BirdListData) GetBirdType() int64 {
	if x != nil {
		return x.BirdType
	}
	return 0
}

func (x *BirdListData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BirdListData) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

type BirdInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID int64 `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
}

func (x *BirdInfoReq) Reset() {
	*x = BirdInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdInfoReq) ProtoMessage() {}

func (x *BirdInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdInfoReq.ProtoReflect.Descriptor instead.
func (*BirdInfoReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{7}
}

func (x *BirdInfoReq) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

type BirdInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID      int64  `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
	BirdName    string `protobuf:"bytes,2,opt,name=BirdName,proto3" json:"BirdName,omitempty"`
	BirdType    int64  `protobuf:"varint,3,opt,name=BirdType,proto3" json:"BirdType,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	PicUrl      string `protobuf:"bytes,5,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime  int64  `protobuf:"varint,7,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
}

func (x *BirdInfoResp) Reset() {
	*x = BirdInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdInfoResp) ProtoMessage() {}

func (x *BirdInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdInfoResp.ProtoReflect.Descriptor instead.
func (*BirdInfoResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{8}
}

func (x *BirdInfoResp) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

func (x *BirdInfoResp) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

func (x *BirdInfoResp) GetBirdType() int64 {
	if x != nil {
		return x.BirdType
	}
	return 0
}

func (x *BirdInfoResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BirdInfoResp) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *BirdInfoResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *BirdInfoResp) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type BirdSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdName string `protobuf:"bytes,1,opt,name=BirdName,proto3" json:"BirdName,omitempty"`
}

func (x *BirdSearchReq) Reset() {
	*x = BirdSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdSearchReq) ProtoMessage() {}

func (x *BirdSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdSearchReq.ProtoReflect.Descriptor instead.
func (*BirdSearchReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{9}
}

func (x *BirdSearchReq) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

type BirdSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*BirdListData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BirdSearchResp) Reset() {
	*x = BirdSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdSearchResp) ProtoMessage() {}

func (x *BirdSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdSearchResp.ProtoReflect.Descriptor instead.
func (*BirdSearchResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{10}
}

func (x *BirdSearchResp) GetList() []*BirdListData {
	if x != nil {
		return x.List
	}
	return nil
}

type BirdDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID int64 `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
}

func (x *BirdDeleteReq) Reset() {
	*x = BirdDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdDeleteReq) ProtoMessage() {}

func (x *BirdDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdDeleteReq.ProtoReflect.Descriptor instead.
func (*BirdDeleteReq) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{11}
}

func (x *BirdDeleteReq) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

type BirdDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdID int64 `protobuf:"varint,1,opt,name=BirdID,proto3" json:"BirdID,omitempty"`
}

func (x *BirdDeleteResp) Reset() {
	*x = BirdDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdDeleteResp) ProtoMessage() {}

func (x *BirdDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_bird_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdDeleteResp.ProtoReflect.Descriptor instead.
func (*BirdDeleteResp) Descriptor() ([]byte, []int) {
	return file_bird_proto_rawDescGZIP(), []int{12}
}

func (x *BirdDeleteResp) GetBirdID() int64 {
	if x != nil {
		return x.BirdID
	}
	return 0
}

var File_bird_proto protoreflect.FileDescriptor

var file_bird_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x69,
	0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x7e, 0x0a, 0x0a, 0x42, 0x69, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x22, 0x25, 0x0a, 0x0b, 0x42, 0x69, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x72, 0x64,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44,
	0x22, 0x99, 0x01, 0x0a, 0x0d, 0x42, 0x69, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69,
	0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x69,
	0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x0e,
	0x42, 0x69, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x0b, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x3d, 0x0a, 0x0c, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x98, 0x01, 0x0a, 0x0c, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x69, 0x72,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x22, 0x25, 0x0a, 0x0b, 0x42,
	0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69,
	0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64,
	0x49, 0x44, 0x22, 0xd8, 0x01, 0x0a, 0x0c, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42,
	0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2b, 0x0a,
	0x0d, 0x42, 0x69, 0x72, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x42, 0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x42, 0x69,
	0x72, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x42,
	0x69, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x69,
	0x72, 0x64, 0x49, 0x44, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x42, 0x69, 0x72, 0x64, 0x49, 0x44, 0x32, 0x9b,
	0x03, 0x0a, 0x04, 0x42, 0x69, 0x72, 0x64, 0x12, 0x3c, 0x0a, 0x07, 0x42, 0x69, 0x72, 0x64, 0x41,
	0x64, 0x64, 0x12, 0x17, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x42, 0x69, 0x72, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x62, 0x69,
	0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0a, 0x42, 0x69, 0x72, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69,
	0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x08,
	0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x42, 0x69, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a,
	0x08, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x62, 0x69, 0x72, 0x64,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45,
	0x0a, 0x0a, 0x42, 0x69, 0x72, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x0a, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x69,
	0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bird_proto_rawDescOnce sync.Once
	file_bird_proto_rawDescData = file_bird_proto_rawDesc
)

func file_bird_proto_rawDescGZIP() []byte {
	file_bird_proto_rawDescOnce.Do(func() {
		file_bird_proto_rawDescData = protoimpl.X.CompressGZIP(file_bird_proto_rawDescData)
	})
	return file_bird_proto_rawDescData
}

var file_bird_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bird_proto_goTypes = []interface{}{
	(*BirdAddReq)(nil),     // 0: birdservice.BirdAddReq
	(*BirdAddResp)(nil),    // 1: birdservice.BirdAddResp
	(*BirdUpdateReq)(nil),  // 2: birdservice.BirdUpdateReq
	(*BirdUpdateResp)(nil), // 3: birdservice.BirdUpdateResp
	(*BirdListReq)(nil),    // 4: birdservice.BirdListReq
	(*BirdListResp)(nil),   // 5: birdservice.BirdListResp
	(*BirdListData)(nil),   // 6: birdservice.BirdListData
	(*BirdInfoReq)(nil),    // 7: birdservice.BirdInfoReq
	(*BirdInfoResp)(nil),   // 8: birdservice.BirdInfoResp
	(*BirdSearchReq)(nil),  // 9: birdservice.BirdSearchReq
	(*BirdSearchResp)(nil), // 10: birdservice.BirdSearchResp
	(*BirdDeleteReq)(nil),  // 11: birdservice.BirdDeleteReq
	(*BirdDeleteResp)(nil), // 12: birdservice.BirdDeleteResp
}
var file_bird_proto_depIdxs = []int32{
	6,  // 0: birdservice.BirdListResp.list:type_name -> birdservice.BirdListData
	6,  // 1: birdservice.BirdSearchResp.list:type_name -> birdservice.BirdListData
	0,  // 2: birdservice.Bird.BirdAdd:input_type -> birdservice.BirdAddReq
	2,  // 3: birdservice.Bird.BirdUpdate:input_type -> birdservice.BirdUpdateReq
	4,  // 4: birdservice.Bird.BirdList:input_type -> birdservice.BirdListReq
	7,  // 5: birdservice.Bird.BirdInfo:input_type -> birdservice.BirdInfoReq
	9,  // 6: birdservice.Bird.BirdSearch:input_type -> birdservice.BirdSearchReq
	11, // 7: birdservice.Bird.BirdDelete:input_type -> birdservice.BirdDeleteReq
	1,  // 8: birdservice.Bird.BirdAdd:output_type -> birdservice.BirdAddResp
	3,  // 9: birdservice.Bird.BirdUpdate:output_type -> birdservice.BirdUpdateResp
	5,  // 10: birdservice.Bird.BirdList:output_type -> birdservice.BirdListResp
	8,  // 11: birdservice.Bird.BirdInfo:output_type -> birdservice.BirdInfoResp
	10, // 12: birdservice.Bird.BirdSearch:output_type -> birdservice.BirdSearchResp
	12, // 13: birdservice.Bird.BirdDelete:output_type -> birdservice.BirdDeleteResp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_bird_proto_init() }
func file_bird_proto_init() {
	if File_bird_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bird_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bird_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bird_proto_goTypes,
		DependencyIndexes: file_bird_proto_depIdxs,
		MessageInfos:      file_bird_proto_msgTypes,
	}.Build()
	File_bird_proto = out.File
	file_bird_proto_rawDesc = nil
	file_bird_proto_goTypes = nil
	file_bird_proto_depIdxs = nil
}
